export {default as greekSalad} from "../../assets/greek salad.webp"
export {default as bruschetta} from "../../assets/bruchetta.png"
export {default as lemonDessert} from "../../assets/lemon dessert.jpg"
export {default as pasta} from "../../assets/pasta.jpeg"
export {default as fries} from "../../assets/fries.jpeg"
export {default as oysters} from "../../assets/oysters.jpeg"
export {default as tilapia} from "../../assets/tilapia.jpeg"
export {default as cheeseBread} from "../../assets/cheeseBread.jpeg"
